channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=25.1
- pip:
  - mlflow==2.22.0
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==2.1.4
name: mlflow-env
